### ISSUE TITLE
EF Core 1.1 support

### ISSUE THREAD

**Issue by allex32** [DevExpress/EF-Core-Security#4]
Good day.

Could you tell me, whether there were plans develop and support EF-Core-Security in future?

I tried to use the` SecurityDbContext` and EF Core 1.1 but I failed.

I can use `context.Add()`/`SaveChanges()` methods, but any selection queries (`context.Find() `or db set using) cause following exception : 

"` System.MissingMethodException . Void Microsoft.EntityFrameworkCore.Query.QueryContextFactory..ctor(Microsoft.EntityFrameworkCore.ChangeTracking.Internal.IStateManager, Microsoft.EntityFrameworkCore.Internal.IConcurrencyDetector, Microsoft.EntityFrameworkCore.ChangeTracking.Internal.IChangeDetector)".`

in line 
`public override IQueryContextFactory QueryContextFactory => GetService<SecurityQueryContextFactory>() ;`
`SecurityDatabaseProviderServices.cs `file.

 At the same time if I use default EF DbContext then all is well.

Is there any way to solve this problem?

Thansk in advance.

**Comment by unfoo** [comment]
Hello,

I've updated the project so that it supports the EF Core 1.1.0.
Even though this project is experimental (mainly for EF Core research purposes) and there is no active development to it, we are always happy to hear your feedback and suggestions or make corrections, if necessary. In particular, our team will be very interested to learn about your real world use-case scenarios and how our project helps you handle them. In addition, it would be great to hear of other options (e.g., ASP.NET Core Identity) you considered prior to visiting our GitHub page and their benefits/weaknesses for your tasks.
